consumerguide/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('food.urls')),
]
admin.site.site_header = 'Finform Consumer Guide Admin Side'

food/urls.py
from django.conf.urls import include, url
from . import views
from django.conf import settings

urlpatterns = [url(r'^food/item_list/$', views.item_list, name='item_list'),
url(r'^post/new/$', views.post_edit, name='post_edit'),
url(r'^food/index/$', views.index, name='index'),
url(r'^food/$', views.home, name='home'),
url(r'^food/register/$', views.register, name='register'),
url(r'^food/login/$',views.user_login, name='login'),
url(r'^food/user_logout/$', views.user_logout, name='logout'),
url(r'^food/add_product/$', views.add_product, name='add_product'),
url(r'^food/food_list/$', views.food_list, name='food_list'),
url(r'^food/forex/$', views.forex, name='forex'),
url(r'^food/forex_rates/$', views.forex_rates, name='forex_rates'),
url(r'^food/forexby_bureau/$', views.forexby_bureau, name='forexby_bureau'),
url(r'^food/loans/$', views.loans, name='loans'),
url(r'^food/table_view/$', views.table_view, name='table_view'),
url(r'^food/price_comparison/$', views.price_comparison, name='price_comparison'),
url(r'^food/forex_comparison/$', views.forex_comparison, name='forex_comparison'),
url(r'^food/loan_comparison/$', views.loan_comparison, name='loan_comparison'),
url(r'^food/cart_comparison/$', views.cart_comparison, name='cart_comparison'),

url(r'^static/(?P<path>.*)$',
        'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
]

food/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

OUTLETS_CHOICES = (
	('Nakumatt', 'Nakumatt'),
	('Tuskys', 'Tuskys'),
	('Naivas', 'Naivas'),
	('Ukwala', 'Ukwala'),
	('Uchumi', 'Uchumi'),
	)

FOOD_CHOICES = (
	('Jogoo Maize Flour', 'Jogoo Maize Flour'),
	('EX Wheat flour', 'EX Wheat flour'),
	('Sugar','Sugar'),
	('Kimbo Cooking Fat', 'Kimbo Cooking Fat'),
	('Broadways Whole Loaf','Broadways Whole Loaf'),
	('Salt', 'Salt'),
	)

WEIGHT_CHOICES = (
	('1', '1 KG'),
	('2', '2 KG'),
	('500', '500 mg'),
	)

BUREAU_CHOICES = (

	('DTBBureau', 'DTBBureau'),
	('SkyBureau', 'SkyBureau'),
	('Nationalbureau', 'Nationalbureau'),
	('IMBureau', 'IMBureau'),
	('FinaBureau', 'FinaBureau'),

	)

CURRENCY_CHOICES = (

	('USD', 'USD'),
	('EURO', 'EURO'),
	('TZSH', 'TZSH'),
	('UGSH', 'UGSH'),
	('BPD', 'BPD'),
	('BPD', 'BPD')

	)


BANK_CHOICES = (

	('Barclays', 'Barclays'),
	('KCB', 'KCB'),
	('Stanchart', 'Stanchart'),
	('Co-op', 'Co-op'),
	('Uwezo', 'Uwezo'),
	('Uwezo', 'Uwezo')

	)


LOAN_CHOICES = (

	('House Mortgage', 'House Mortgage'),
	('Biashara', 'Biashar'),
	('Personal', 'Personal'),
	('Chama', 'Chama'),
	('Car', 'Car'),
	('Commercial', 'Commercial')

	)







class Costs(models.Model):
	itemname = models.CharField(max_length=200, choices=FOOD_CHOICES)
	unitcost = models.IntegerField()
	weight = models.IntegerField(default = 1, choices=WEIGHT_CHOICES)
	dateprovided = models.DateTimeField(default = timezone.now)
	location = models.CharField(max_length=200)
	retailer = models.CharField(max_length=200, choices=OUTLETS_CHOICES)
	

	def __unicode__(self):
		return self.itemname

class Outlet(models.Model):
	name = models.CharField(max_length=200)
	item = models.ManyToManyField(Costs)


	def __unicode__(self):
		return self.name

class Region(models.Model):
	name = models.CharField(max_length=200)
	outlet = models.ManyToManyField(Outlet)

	def __unicode__(self):
		return self.name

class UserProfile(models.Model):
	user = models.OneToOneField(User)
	website = models.URLField(blank=True)
	picture = models.ImageField(upload_to='profile_images', blank=True)

	def __unicode__(self):
		return self.user.username



class Banks(models.Model):
	bank_name = models.CharField(max_length=300)
	bank_type = models.CharField(max_length=300)
	webpage = models.CharField(max_length=300)

	def __unicode__(self):
		return self.bank_name


class Loans(models.Model):
	loan_name = models.CharField(max_length=250, choices=LOAN_CHOICES)
	loan_description = models.CharField(max_length=400)
	requirements = models.CharField(max_length=300)
	loan_amount = models.IntegerField(default = 50000)
	bank = models.CharField(max_length=300 ,  default = "Barclays", blank=True, null=True, choices=BANK_CHOICES)
	#bank = models.ForeignKey(Banks)


	def __unicode__(self):
		return self.loan_name


class Bureau(models.Model):
	#inst_id = models.IntegerField()
	inst_name = models.CharField(max_length=300, default = "SkyBureau", blank=True, null=True, choices=BUREAU_CHOICES)
	webpage = models.CharField(max_length=300)
	#type_name = models.ForeignKey(Institution_type, on_delete=models.CASCADE)
	bureau_type = models.CharField(max_length=300)

	def __unicode__(self):
		return self.inst_name


class Forex(models.Model):
	currency_name = models.CharField(max_length=300, choices=CURRENCY_CHOICES)
	buying_price = models.IntegerField()
	selling_price = models.IntegerField()
	#inst_id = models.ForeignKey(Instititution, on_delete=models.CASCADE)
	bureau = models.ForeignKey(Bureau, on_delete=models.CASCADE)

	def __unicode__(self):
		return self.currency_name






#class Institution_type(models.Model):
	#type_id = models.IntegerField()
	#inst_id = models.ForeignKey(Instititution, on_delete=models.CASCADE)
	#type_name = models.CharField(max_length=300)

food/forms.py
from django import forms

from .models import (
	Costs,
	UserProfile,
	OUTLETS_CHOICES, FOOD_CHOICES
)

from .models import (
	Bureau,
	Forex,
	BUREAU_CHOICES
)
from .models import (
	Loans,
	BANK_CHOICES
)

from django.contrib.auth.models import User

class CostForm(forms.ModelForm):

	class Meta:
		model = Costs
		fields = ('itemname', 'unitcost', 'weight','retailer')


class UserForm(forms.ModelForm):
	 password = forms.CharField(widget=forms.PasswordInput())

	 class Meta:
	 	model = User
	 	fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('website', 'picture')



class ComparisonForm(forms.ModelForm):
	retailer = forms.MultipleChoiceField( 
		widget=forms.CheckboxSelectMultiple, choices=OUTLETS_CHOICES)

	class Meta:
		model = Costs 
		fields = ('itemname',)
	

	def clean_retailer(self):

		data = self.cleaned_data['retailer']
		if len(data) < 2:
			raise forms.ValidationError("You must select at least two retailers")


		return data	



class CartComparisonForm(forms.ModelForm):
	retailer = forms.MultipleChoiceField( 
		widget=forms.CheckboxSelectMultiple, choices=OUTLETS_CHOICES)


	itemname = forms.MultipleChoiceField(choices = FOOD_CHOICES,
		 widget  = forms.CheckboxSelectMultiple, )

	class Meta:
		model = Costs 
		# fields = ('itemname',)
		exclude = ['unitcost', 'weight', 'dateprovided','location','itemname', 'retailer']
	

	# def clean_retailer(self):

	# 	data = self.cleaned_data['retailer']
	# 	if len(data) < 2:
	# 		raise forms.ValidationError("You must select at least two retailers")

	# 	return data	





class ForexComparisonForm(forms.ModelForm):
	bureau = forms.MultipleChoiceField(
		widget=forms.CheckboxSelectMultiple, choices=BUREAU_CHOICES)


	class Meta:
		model = Forex
		fields = ('currency_name',)


	def clean_bureau(self):

		data = self.cleaned_data['bureau']
		if len(data) < 2:
			raise forms.ValidationError("You must select atleast two forex bureaus")


		return data



class LoanComparisonForm(forms.ModelForm):
	bank = forms.MultipleChoiceField(
		widget=forms.CheckboxSelectMultiple, choices=BANK_CHOICES)


	class Meta:
		model = Loans
		fields = ('loan_name',)


	def clean_bureau(self):

		data = self.cleaned_data['banks']
		if len(data) < 2:
			raise forms.ValidationError("You must select atleast two banks")


		return data

		

food/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Costs
from .models import Loans
from .models import Forex
from.models import Bureau
from .forms import CostForm
from .forms import UserForm, UserProfileForm
from .forms import ComparisonForm
from .forms import ForexComparisonForm
from .forms import LoanComparisonForm
from .forms import CartComparisonForm
from django.db.models import Count
from django.db.models import F
from django.views.generic.edit import FormView

from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import logout

# Create your views here.


def item_list(request):
	#costs = Costs.objects.filter(dateprovided__lte=timezone.now()).order_by('dateprovided')
	#costs = Costs.objects.filter(itemname = "sugar")
	#costs = Costs.objects.all()
	#costs = Costs.objects.annotate(number_of_entries=Count('unitcost'))
	costs = Costs.objects.values('unitcost', 'itemname','retailer','weight').annotate(frequency = Count('unitcost')).order_by('-frequency')
	results = []
	processed_items = [] 

	for cost in costs:
		if cost['itemname'] not in processed_items:
			processed_items.append(cost['itemname'])
			temp = {
				"frequency": cost['frequency'],
				"itemname": cost['itemname'],
				"unitcost": cost['unitcost'],
				"retailer": cost['retailer'],
				"weight": cost['weight'],
			}
			for item in costs:
				if item['itemname'] == temp['itemname']:
					if item['frequency'] > temp['frequency']:
						temp['frequency'] = item['frequency']
						temp['unitcost'] = item['unitcost']
						temp['retailer'] = item['retailer']
						temp['weight'] = item['weight']
			results.append(temp)
	
	#print(results)	
	# highest_frequency = costs[0]
	#print(costs[0].number_of_entries)
	return render(request, 'food/item_list.html', {'costs':results })


def food_list(request):
	
	costs = Costs.objects.values('unitcost', 'itemname','retailer','weight').annotate(frequency = Count('unitcost')).order_by('-frequency')
	results = []
	processed_items = [] 

	for cost in costs:
		if cost['itemname'] not in processed_items:
			processed_items.append(cost['itemname'])
			temp = {
				"frequency": cost['frequency'],
				"itemname": cost['itemname'],
				"unitcost": cost['unitcost'],
				"retailer": cost['retailer'],
				"weight": cost['weight'],
			}
			for item in costs:
				if item['itemname'] == temp['itemname']:
					if item['frequency'] > temp['frequency']:
						temp['frequency'] = item['frequency']
						temp['unitcost'] = item['unitcost']
						temp['retailer'] = item['retailer']
						temp['weight'] = item['weight']
			results.append(temp)
	
	return render(request, 'food/food_list.html', {'costs':results })



def table_view(request):
	
	costs = Costs.objects.values('unitcost', 'itemname').annotate(frequency = Count('unitcost')).order_by('-frequency')
	results = []
	processed_items = [] 

	for cost in costs:
		if cost['itemname'] not in processed_items:
			processed_items.append(cost['itemname'])
			temp = {
				"frequency": cost['frequency'],
				"itemname": cost['itemname'],
				"unitcost": cost['unitcost']
			}
			for item in costs:
				if item['itemname'] == temp['itemname']:
					if item['frequency'] > temp['frequency']:
						temp['frequency'] = item['frequency']
						temp['unitcost'] = item['unitcost']
			results.append(temp)
	
	return render(request, 'food/table_view.html', {'costs':results })


def post_edit(request):
	#if request.method == "POST":
		form = CostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.dateprovided = timezone.now()
			post.save()
	
        	return render(request, 'food/post_edit.html', {'form': form})


def add_product(request):
	#if request.method == "POST":
		form = CostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.dateprovided = timezone.now()
			post.save()
	
        	return render(request, 'food/add_product.html', {'form': form})


def home(request):
	#costs = Costs.objects.filter(dateprovided__lte=timezone.now()).order_by('dateprovided')
	#costs = Costs.objects.filter(itemname = "sugar")
	#costs = Costs.objects.all()
	#costs = Costs.objects.annotate(number_of_entries=Count('unitcost'))
	costs = Costs.objects.values('unitcost', 'itemname').annotate(frequency = Count('unitcost')).order_by('-frequency')
	results = []
	processed_items = [] 

	for cost in costs:
		if cost['itemname'] not in processed_items:
			processed_items.append(cost['itemname'])
			temp = {
				"frequency": cost['frequency'],
				"itemname": cost['itemname'],
				"unitcost": cost['unitcost']
			}
			for item in costs:
				if item['itemname'] == temp['itemname']:
					if item['frequency'] > temp['frequency']:
						temp['frequency'] = item['frequency']
						temp['unitcost'] = item['unitcost']
			results.append(temp)
	
	#print(results)	
	# highest_frequency = costs[0]
	#print(costs[0].number_of_entries)
	return render(request, 'food/home.html', {'costs':results })

def index(request):

	return render(request, 'food/index.html', {})


#user registration
def register(request):

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
            'food/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )



#user login
def user_login(request):

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
                # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
                # because the request.POST.get('<variable>') returns None, if the value does not exist,
                # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/food/index')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your Rango account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'food/login.html', {})



# Use the login_required() decorator to ensure only those logged in can access the view.

def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)

    # Take the user back to the homepage.
    return HttpResponseRedirect('/food/index/')


def forex(request):

food/templates/food/forexby_bureau.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<head>
<title>Carpool</title>
<!-- must have -->
    <link href="{% static "food/css/bootstrap.css" %}" type="text/css" rel="stylesheet" />
    	<link href="{% static "food/css/bootstrap-theme.css" %}" type="text/css" rel="stylesheet" />
      <link href="{% static "food/css/style.css" %}" type="text/css" rel="stylesheet" />
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato:400,700,700italic' rel='stylesheet' type='text/css'>


<script type="text/javascript" src="{% static "food/js/jquery-1.7.1.min.js" %}"></script>
<script type="text/javascript" src="{% static "food/js/jquery-ui-1.8.23.min.js" %}"></script><script type="text/javascript">
$(document).ready(function(){
  $(".my-account-button").click(function(){
	$(".my-account-details").fadeToggle("fast", function(){
	  if($(".my-account-details").css('display') == "none")
		$(".my-account-button").removeClass("active");
	  else
		$(".my-account-button").addClass("active");
	});
  });
});
</script>
<link rel="shortcut icon" href="http://www.carpoolingscript.com/demo/carpooling/themes/carpooling/assets/img/favicon.ico">
</head>

<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=1618861935012037";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script> 
<style type="text/css"> iframe[id^='twitter-widget-0']{ width:280px !important;} </style>


                                        
<div class="col-lg-6 col-md-6 col-sm-8 col-xs-12">        
                             <ul class="top-nav new-top-nav">
             <li> <a href="/food/food_list/" class="top-signup"> FOOD PRICES </a> </li>
              <li> <a href="/food/loans/" class="top-signup"> LOANS </a> </li>              
    
            <li> <a href="/food/forex_rates/" class="top-signup"> FOREX </a> </li>
            {% if user.is_authenticated %}
            <li> <a href="/food/user_logout/" class=""> logout </a> </li>
            {% else %}
             <li> <a href="/food/register/" class="top-signup"> REGISTER </a> </li>
             <li> <a href="/food/login/" class=""> LOGIN </a> </li>
             {% endif %}
             <li> <p class=""> {% if user.is_authenticated %}
                Hello {{ user.username }}!
                  {% else %}
                  Hello user.Login for better features!
                  {% endif %} </p> </li>
           
                  </ul>
                        </ul>                     
        </div>
  </div>
</div><script type="text/javascript" src="{% static "food/js/jquery.validate.js" %}"></script>
<script type="text/javascript" src="{% static "food/js/travel-details-rules.js" %}"></script>
<script type="text/javascript" src="{% static "food/js/notification/goNotification.js" %}"></script><link href="{% static "food/js/notification/goNotification.css" %}" rel="stylesheet" type="text/css">
<script>
$(document).ready(function() {	
	
				$('#txtphone').attr('readonly', false);
		$('#txtphone').removeClass('disable');
				
				
			
	});
</script>
<div class="container-fluid margintop40">
        <div class="container">
            <div class="row margintop40">  

      <div class="col-lg-5 col-md-5 col-sm-6 padding20 reg-main">
        <ul class="reg-cont margintop40">
          <li class="margintop40">
            <h3>Most comprehensive web based consumer guide !</h3><br>
            <p>A connecting site for shoppers looking for the best value for their money.</p><br/> 
           <p> Sign up and view food prices, loan rates and the shilling exchange rates.Even better customize according to your needs.  </p><br/>
           <p>Post your most recent food purchase prices here and help us help others .</p> 
          </li>
        </ul>
      </div>      

      <div class="col-lg-6 col-md-6 col-sm-6 fleft padding20 grey-bg reg-main">
        <h2 class="center marginbot40">  Current exchange rates  </h2>
        <h3 class="center marginbot40"> To view more <a href="/food/add_product/">Click here</a> </h3>

         

   <table class="table">
   
<thead><th>Instititution Name</th><th>Buying Price</th><th>Selling price</th><th></th></thead>
{% for instititutions in instititution %}

    <tr>

        
        <td><!-- {{ instititutions.inst_name }} --></td>
       {% for forex in instititutions.forex_set.all %}
       <tr>
       <td>{{ instititutions.inst_name }}<br></td>
        <td>{{forex.currency_name}}<br></td>
       <td> {{forex.buying_price}}<br></td>
        <td>{{forex.selling_price}}<br/></td>
       {% endfor %}
         <!-- <td> {{ forexrates.instititution }}</td> -->
       
       </tr>

       <!-- <td>{{ cost.location|linebreaks }}</td> -->
</tr>

        {% endfor %}
</table>
      </div>
      <!-- Right -->
    </div>
  </div>
</div>
<div class="container-fluid cs-blue-bg margintop40">
  <div class="container">
    <div class="margintop40 marginbot40 center gtcont">
      <h2 class="colorwhite"> Got a Question? </h2>
      <p class="padding20 row colorwhite">We're here to help. Get in touch via contact us or hit us an email</p>
      <a href="#"> Contact Now </a> </div>
  </div>
</div>

 <div class="container-fluid footerbg paddingtopbot40">
  <div class="container">
    <div class="row footer">
      
        		<div class="col-lg-4 col-md-6 col-sm-6  col-xs-12 log-subs fleft">
			      <div class="logo"> <a href="/food/index"> <img src="{% static "img/finformlogo.png" %}"> </a> </div>
			      <div class="ftr-subs margintop20 marginbot10 fleft lgrey-text">
			        <p class="margintop20 colorwhite size17"> Subscribe to Newsletter </p>
			        <input type="text" placeholder="Email Address" class="emaddr">
			        <input type="submit" value="Sign Up" class="blue-bg white-text subs-brd">
      </div>
      <p class="colorwhite margintop20 size14 fleft">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ille, ut dixi, vitiose. Non laboro, inquit, de nomine. Duo Reges:</p>
    </div>

			    <div class="col-lg-2 col-md-6 col-sm-6  col-xs-12">
			      <h3 class="colorwhite size18 marginbot10"> Sitemap </h3>
      <ul class="fleft ftr-ste">
        <li> <a href="#"> Blog </a> </li>
        <li> <a href="#"> Company Directory </a> </li>
        <li> <a href="#"> Contact </a> </li>
        <li> <a href="#"> Find a Candidate  </a> </li>
        <li> <a href="#"> Find a Car </a> </li>       
      </ul>
    </div>
    
<div class="hideall">
   <div class="fleft width20p ftr-arti">
      <div class="fb-page" data-href="https://www.facebook.com/pages/Carpoolingscript/807705419319976?ref=aymt_homepage_panel" data-width="180" data-height="370" data-hide-cover="false" data-show-facepile="true" data-show-posts="true">
      <div class="fb-xfbml-parse-ignore">
      <blockquote cite="https://www.facebook.com/pages/Carpoolingscript/807705419319976?ref=aymt_homepage_panel">
      <a href="https://www.facebook.com/pages/Carpoolingscript/807705419319976?ref=aymt_homepage_panel">Carpoolingscript</a>
      </blockquote>
      </div>
      </div>
   </div> 
   <div class="fright width20p ftr-arti"> 
    <a class="twitter-timeline" href="https://twitter.com/carpoolingscrip" data-widget-id="588318601595125760">Tweets by @carpoolingscrip</a> 
    </div>

</div>

    </div>
  </div>
</div>


    <div class="container-fluid ftrbg padding10">
  <div class="container">
    <div class="row footer colorwhite">
      <p class="size14 fleft"> &copy; 2015 Carpooling - All Rights Reserved. </p>
      <div class="fright">
        <ul class="fleft soc-ico">
            <li> <a href="#"> <img src="http://www.carpoolingscript.com/demo/carpooling/themes/carpooling/assets/img/fb-ico.png"> </a> </li>
            <li> <a href="#"> <img src="http://www.carpoolingscript.com/demo/carpooling/themes/carpooling/assets/img/tw-ico.png"> </a> </li>
            <li> <a href="#"> <img src="http://www.carpoolingscript.com/demo/carpooling/themes/carpooling/assets/img/gp-ico.png"> </a> </li>
            <li> <a href="#"> <img src="http://www.carpoolingscript.com/demo/carpooling/themes/carpooling/assets/img/in-ico.png"> </a> </li>
            <li> <a href="#"> <img src="http://www.carpoolingscript.com/demo/carpooling/themes/carpooling/assets/img/pin-ico.png"> </a> </li>
            <li> <a href="#"> <img src="http://www.carpoolingscript.com/demo/carpooling/themes/carpooling/assets/img/vi-ico.png"> </a> </li>
        </ul>
      </div>
    </div>
  </div>
</div>
</body>
</html>

food/templates/food/login1.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Is anyone getting tired of repeatedly entering the header over and over?? -->
        <title>Rango</title>
    </head>

    <body>
        <h1>Login to Rango</h1>

        <form id="login_form" method="post" action="/food/login/">
            {% csrf_token %}
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>

    </body>
</html>